// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_scenario from "./routes/api/scenario.ts";
import * as $hk_theme_id_chat from "./routes/hk/[theme_id]/chat.tsx";
import * as $hk_themes from "./routes/hk/themes.tsx";
import * as $index from "./routes/index.tsx";
import * as $japanese_theme_id_chat from "./routes/japanese/[theme_id]/chat.tsx";
import * as $japanese_themes from "./routes/japanese/themes.tsx";
import * as $StructuredChatPage from "./islands/StructuredChatPage.tsx";
import * as $ThemesPage from "./islands/ThemesPage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/scenario.ts": $api_scenario,
    "./routes/hk/[theme_id]/chat.tsx": $hk_theme_id_chat,
    "./routes/hk/themes.tsx": $hk_themes,
    "./routes/index.tsx": $index,
    "./routes/japanese/[theme_id]/chat.tsx": $japanese_theme_id_chat,
    "./routes/japanese/themes.tsx": $japanese_themes,
  },
  islands: {
    "./islands/StructuredChatPage.tsx": $StructuredChatPage,
    "./islands/ThemesPage.tsx": $ThemesPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
